# Anna Pankiewicz
# CS3800 Operating Systems

main: main.cpp file.cpp permissions.cpp shell.cpp
	g++ -std=c++11 main.cpp file.cpp permissions.cpp \
	    user.cpp shell.cpp -o shell

.PHONY: clean
clean:
	rm shell
